services:
    # nginx
    web:
        image: nginx:1.27.4
        ports:
            - "${WEB_OUTER_PORT}:${WEB_INNER_PORT}"
        volumes:
            - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
    # php
    app:
        build:
            dockerfile: ./php/Dockerfile
            target: app
        volumes:
            - /var/www/html/vendor
            - ./:/var/www/html
    # mysql
    db:
        image: mysql:8.0
        volumes:
            - ./mysqldata:/var/lib/mysql
        ports:
            - "${DB_OUTER_PORT}:${DB_PORT}"
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}

    # redis
